export type Position = 'Safelane' | 'Mid' | 'Offlane' | 'Soft Support' | 'Hard Support';

// Primary position per hero — based on Dota 2 patch 7.41 meta
const HERO_POSITION_MAP: Record<string, Position> = {
  // ── Safelane (Pos 1 — Carry) ──────────────────────────────────────────
  'Anti-Mage':        'Safelane',
  'Juggernaut':       'Safelane',
  'Morphling':        'Safelane',
  'Phantom Lancer':   'Safelane',
  'Sniper':           'Safelane',
  'Drow Ranger':      'Safelane',
  'Gyrocopter':       'Safelane',
  'Chaos Knight':     'Safelane',
  'Luna':             'Safelane',
  'Bloodseeker':      'Safelane',
  'Sven':             'Safelane',
  'Faceless Void':    'Safelane',
  'Wraith King':      'Safelane',
  'Clinkz':           'Safelane',
  'Weaver':           'Safelane',
  'Ursa':             'Safelane',
  'Phantom Assassin': 'Safelane',
  'Naga Siren':       'Safelane',
  'Slark':            'Safelane',
  'Medusa':           'Safelane',
  'Terrorblade':      'Safelane',
  'Riki':             'Safelane',
  'Troll Warlord':    'Safelane',
  'Spectre':          'Safelane',
  'Lifestealer':      'Safelane',
  'Arc Warden':       'Safelane',
  'Monkey King':      'Safelane',
  'Lone Druid':       'Safelane',
  'Mirana':           'Safelane',
  'Razor':            'Safelane',
  'Tiny':             'Safelane',
  'Huskar':           'Safelane',
  'Leshrac':          'Safelane',

  // ── Mid (Pos 2) ───────────────────────────────────────────────────────
  'Shadow Fiend':           'Mid',
  'Puck':                   'Mid',
  'Lina':                   'Mid',
  'Zeus':                   'Mid',
  'Kunkka':                 'Mid',
  'Death Prophet':          'Mid',
  'Queen of Pain':          'Mid',
  'Pugna':                  'Mid',
  'Templar Assassin':       'Mid',
  'Tinker':                 'Mid',
  'Storm Spirit':           'Mid',
  'Outworld Destroyer':     'Mid',
  'Invoker':                'Mid',
  'Alchemist':              'Mid',
  'Dragon Knight':          'Mid',
  'Viper':                  'Mid',
  'Windranger':             'Mid',
  'Skywrath Mage':          'Mid',
  'Ember Spirit':           'Mid',
  'Void Spirit':            'Mid',
  'Broodmother':            'Mid',
  'Muerta':                 'Mid',
  'Meepo':                  'Mid',
  'Kez':                    'Mid',
  'Magnus':                 'Mid',
  'Visage':                 'Mid',
  'Bristleback':            'Mid',

  // ── Offlane (Pos 3) ───────────────────────────────────────────────────
  'Axe':               'Offlane',
  'Bane':              'Offlane',
  'Dark Seer':         'Offlane',
  'Sand King':         'Offlane',
  'Tidehunter':        'Offlane',
  'Pudge':             'Offlane',
  'Spirit Breaker':    'Offlane',
  'Enigma':            'Offlane',
  'Brewmaster':        'Offlane',
  'Clockwerk':         'Offlane',
  'Night Stalker':     'Offlane',
  'Doom':              'Offlane',
  'Batrider':          'Offlane',
  'Legion Commander':  'Offlane',
  'Elder Titan':       'Offlane',
  'Timbersaw':         'Offlane',
  'Centaur Warrunner': 'Offlane',
  'Underlord':         'Offlane',
  'Phoenix':           'Offlane',
  'Slardar':           'Offlane',
  'Mars':              'Offlane',
  'Pangolier':         'Offlane',
  'Primal Beast':      'Offlane',
  'Dawnbreaker':       'Offlane',
  'Marci':             'Offlane',
  'Lycan':             'Offlane',
  'Beastmaster':       'Offlane',
  'Nature\'s Prophet': 'Offlane',
  'Enchantress':       'Offlane',
  'Venomancer':        'Offlane',
  'Lifestealer':       'Offlane',
  'Dark Willow':       'Offlane',
  'Treant Protector':  'Offlane',
  'Abaddon':           'Offlane',
  'Jakiro':            'Offlane',
  'Techies':           'Offlane',
  'Doom':              'Offlane',

  // ── Soft Support (Pos 4) ──────────────────────────────────────────────
  'Shadow Shaman':     'Soft Support',
  'Bounty Hunter':     'Soft Support',
  'Nyx Assassin':      'Soft Support',
  'Rubick':            'Soft Support',
  'Shadow Demon':      'Soft Support',
  'Earthshaker':       'Soft Support',
  'Disruptor':         'Soft Support',
  'Earth Spirit':      'Soft Support',
  'Ogre Magi':         'Soft Support',
  'Tusk':              'Soft Support',
  'Chen':              'Soft Support',
  'Hoodwink':          'Soft Support',
  'Grimstroke':        'Soft Support',
  'Snapfire':          'Soft Support',
  'Lion':              'Soft Support',
  'Ringmaster':        'Soft Support',
  'Keeper of the Light': 'Soft Support',
  'Ancient Apparition': 'Soft Support',
  'Witch Doctor':      'Soft Support',
  'Jakiro':            'Soft Support',
  'Mirana':            'Soft Support',
  'Crystal Maiden':    'Soft Support',
  'Lich':              'Soft Support',

  // ── Hard Support (Pos 5) ──────────────────────────────────────────────
  'Dazzle':            'Hard Support',
  'Io':                'Hard Support',
  'Oracle':            'Hard Support',
  'Omniknight':        'Hard Support',
  'Undying':           'Hard Support',
  'Vengeful Spirit':   'Hard Support',
  'Winter Wyvern':     'Hard Support',
  'Warlock':           'Hard Support',
  'Abaddon':           'Hard Support',
  'Treant Protector':  'Hard Support',
};

// Fallback for heroes not in the map
function fallbackPosition(roles: string[], primary_attr: string): Position {
  const r = new Set(roles ?? []);
  if (r.has('Support')) return r.has('Disabler') || r.has('Initiator') ? 'Soft Support' : 'Hard Support';
  if (r.has('Carry')) return 'Safelane';
  if (r.has('Initiator') || r.has('Durable')) return 'Offlane';
  if (primary_attr === 'int') return 'Mid';
  return 'Offlane';
}

export function getHeroPosition(localized_name: string, roles: string[], primary_attr: string): Position {
  return HERO_POSITION_MAP[localized_name] ?? fallbackPosition(roles, primary_attr);
}
